apps/users/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index),
    url(r'^combined/', views.disp_login_reg, name='disp_reg_login'),
    url(r'^register/', views.disp_reg, name='disp_reg'),
    url(r'^users/new/', views.register, name='create_user'),
    url(r'^login/$', views.disp_login, name='disp_login'),
    url(r'^login/process/$', views.login, name='do_login'),
    url(r'^logout/$', views.logout, name='do_logout'),
    url(r'^users/list/$', views.disp_users, name='disp_users'),

]

ebdjango/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.users.urls', namespace='users')),
]

apps/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
import isvalid
from error import Error
import bcrypt

# Create your models here.


class UserManager(models.Manager):
    def validateRegistration(self, data):
        errors = []
        if 'first_name' in data and 'last_name' in data and 'email' in data and 'password' in data and 'c_password' in data:
            valid, msg = isvalid.first_name(data['first_name'])
            if not valid:
                errors.append(Error('first_name', msg))
            valid, msg = isvalid.last_name(data['last_name'])
            if not valid:
                errors.append(Error('last_name', msg))
            valid, msg = isvalid.email(data['email'])
            if not valid:
                errors.append(Error('email', msg))
            valid, msg = isvalid.password(
                data['password'], data['c_password'])
            if not valid:
                errors.append(Error('password', msg))
            # if all the fields look good make sure the user doesnt already exist
            if not errors:
                existing_users = self.filter(email=data['email'])
                if existing_users:
                    errors.append(Error(
                        'email', 'email already registered if you have forgoten your password please use the password reset link'))

        else:
            errors.append(
                Error('form', 'Something went wrong please try to submit the form again'))
        if errors:
            return (False, errors)
        else:

            return (True, data)

    def add(self, data):
        valid, errors = self.validateRegistration(data)
        if valid:
            hashedpwd = bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt())
            return (valid, self.create(first_name=data['first_name'],
                                       last_name=data['last_name'],
                                       email=data['email'],
                                       password=hashedpwd,))
        else:
            return (valid, errors)

    def validateLogin(self, data):
        errors = []
        users = {}
        if 'email' in data and 'password' in data:
            valid, msg = isvalid.email(data['email'])
            if not valid:
                errors.append(Error('email', msg))
            # if the email looks good check if the user password matches
            if not errors:
                users = self.filter(email=data['email'])
                if len(users) != 1:
                    errors.append(Error('email, password', 'something went wrong please contact customer support'))
                else:
                    if bcrypt.hashpw(data['password'].encode(), users[0].password.encode()) != users[0].password:
                        errors.append(Error('email, password', 'incorrect email and password combination please try again'))
        else:
            errors.append(
                Error('form', 'Something went wrong please try to submit the form again'))
        if errors:
            return (False, errors)
        else:
            return (True, users[0])


class User(models.Model):
    objects = UserManager()
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}: {} {} {}'.format(self.id, self.first_name, self.last_name, self.email)

    def __unicode__(self):
        return '{}: {} {} {}'.format(self.id, self.first_name, self.last_name, self.email)

apps/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse, redirect
from django.views.decorators.http import require_http_methods
from django.contrib import messages
from django.core.urlresolvers import reverse
from .models import User
import base64


# Create your views here.
def logged_in(ses):
    print ses
    if 'user_id' in ses:
        try:
            User.objects.get(id=ses['user_id'])
            return True
        except:
            return False
    return False

def index(request):
    """ This is a good sample of how to protect a view """
    if logged_in(request.session):
        #if logged in do the stuff you need to do
        return redirect('users:disp_users')
    else:
        return render(request, 'users/combined.html')

def disp_users(request):
    """ This is a good sample of how to protect a view """
    print 'disp users'
    if logged_in(request.session):
        #if logged in do the stuff you need to do
        context = {'users': User.objects.all()}
        return render(request, 'users/list.html', context)
    else:
        #if not logged in send to login page with next page to go to after login
        next_pg = base64.urlsafe_b64encode(request.path)
        return redirect(reverse('users:disp_login') + '?next={}'.format(next_pg))


def disp_reg(request):
    return render(request, 'users/register.html')


@require_http_methods(['POST'])
def register(request):
    valid, data = User.objects.add(request.POST)
    if valid:
        request.session['user_id'] = data.id
        return redirect(reverse('users:disp_users'))
    else:
        for i in data:
            messages.add_message(request, messages.ERROR, i.message)
    # can we do this better
    return redirect(reverse('users:disp_reg'))

def disp_login_reg(request):
    return render(request, 'users/combined.html')

def disp_login(request):
    context = {}
    if 'next' in request.GET:
        context['next_pg'] = request.GET['next']
    return render(request, 'users/login.html', context)


@require_http_methods(['POST'])
def login(request):
    """Validates user is email and password, sets session variables"""
    valid, data = User.objects.validateLogin(request.POST)
    if valid:
        request.session['user_id'] = data.id
        print 'valid login'
        next_pg = '/'
        if 'next_pg' in request.POST and len(request.POST['next_pg'])>0:
            print 'process next_pg'
            enc = request.POST['next_pg']
            next_pg = base64.urlsafe_b64decode(enc.encode('ascii'))
        print next_pg
        return redirect(next_pg)
    else:
        for i in data:
            messages.add_message(request, messages.ERROR, i.message)
        #TODO: looses next page if they type the password wrong
        return redirect('users:disp_login')

def logout(request):
    request.session.flush()
    messages.add_message(request, messages.SUCCESS, 'You have been logged out')
    return redirect('users:disp_login')

apps/users/templates/users/_login.html
<form action="{% url 'users:do_login' %}" method="POST">
    {% csrf_token %}
    <h2>Login</h2>
    {% if messages %}
    <div class="alert alert-danger">
        <ul class="messages">
            {% for msg in messages %}
            <li>{{msg.message}}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    <input type="hidden" name="next_pg" value="{{ next_pg }}" />
    <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" class="form-control" name="email" id="email" aria-describedby="email_help" placeholder="Enter your email">
        <small id="email_help" class="form-text text-muted">Enter your email</small>
    </div>
    <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" class="form-control" name="password" id="password" placeholder="">
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

apps/users/templates/users/_register.html
<form action="{% url 'users:create_user' %}" method="POST">
    {% csrf_token %}
    <h2>Registration</h2>
    {% if messages %}
    <div class="alert alert-danger">
        <ul class="messages">
            {% for msg in messages %}
            <li>{{msg.message}}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    <div class="form-group">
        <label for="first_name">First Name:</label>
        <input type="text" class="form-control" name="first_name" id="first_name" aria-describedby="first_name_help" placeholder="Enter your first name">
        <small id="first_name_help" class="form-text text-muted">Enter your first name</small>
    </div>
    <div class="form-group">
        <label for="last_name">Last Name:</label>
        <input type="text" class="form-control" name="last_name" id="last_name" aria-describedby="last_name_help" placeholder="Enter your last name">
        <small id="last_name_help" class="form-text text-muted">Enter your last name</small>
    </div>
    <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" class="form-control" name="email" id="email" aria-describedby="email_help" placeholder="Enter your email">
        <small id="email_help" class="form-text text-muted">Enter your email</small>
    </div>
    <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" class="form-control" name="password" id="password" placeholder="">
    </div>
    <div class="form-group">
        <label for="c_password">Confirm Password:</label>
        <input type="password" class="form-control" name="c_password" id="c_password" placeholder="">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

apps/users/templates/users/combined.html
{% extends 'base.html' %} 
{% block content %} 
    <div style="display:flex; justify-content:space-around">
    {% include "./register.html" %} 
    {% include "./login.html" %} 
    </div>

{% endblock content %}

apps/users/templates/users/list.html
{% extends 'base.html' %} {% block content %}
<table class="table table-striped">
    <thead class="thead-inverse">
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Password</th>
            <th>Date Added</th>

        </tr>
    </thead>
    <tbody>
        {% if users %} {% for user in users %}
        <tr>
            <td scope="row">{{user.first_name}}</td>
            <td>{{user.last_name}}</td>
            <td>{{user.email}}</td>
            <td>{{user.password}}</td>
            <td>{{user.created_at|date:"SHORT_DATETIME_FORMAT"}}</td>
        </tr>
        {% endfor %} {% endif %}
    </tbody>
</table>
<!--<pre> {% filter force_escape %} {% debug %} {% endfilter %} </pre>-->
{% endblock content %}

apps/users/templates/users/login.html
{% extends 'base.html' %} {% block content %}
{% include "./_login.html" %} 
{% endblock content %}

apps/users/templates/users/register.html
{% extends 'base.html' %} {% block content %}
{% include "./_register.html" %} 
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login Register</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ"
        crossorigin="anonymous">
</head>

<body>
    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
        crossorigin="anonymous"></script>
    {% load static %}
    <!--<script src="{% static 'js/scripts.js' %}"></script>-->

</body>

</html>